Update Playwright to v 1.36.2
We're seeing an error in CI:

1) [setupDev] › auth.setup.ts:5:6 › authenticate ─────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1071/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.36.2. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.34.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.36.2-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝